version: '2'
services:
    SmokePing:
        image: smokeping
        container_name: smokeping
        ports:
            - '8888:80'
        volumes:
            - "./config:/etc/smokeping/config.d:ro"
            - "./logdata:/var/lib/smokeping:rw"
        environment:
            - TZ=PST8PDT

        ### Allows to auto-start with Docker
        restart: always
